version: '3.3'
services:
  keestash_web:
    container_name: keestash_web
    build:
      context: ./config/docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./config/docker/web/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/docker/web/apache/keestash.conf:/etc/apache2/sites-available/000-default.conf
      - ~/config/mkcert/certificates/cert.pem:/etc/apache2/ssl/cert.pem
      - ~/config/mkcert/certificates/cert-key.pem:/etc/apache2/ssl/cert-key.pem
    ports:
      - '8000:80'
      - '8080:443'
  db:
    container_name: mysql8
    build:
      context: ./config/docker/db
      dockerfile: Dockerfile
    platform: linux/amd64
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keestash
      MYSQL_DATABASE: keestash
      MYSQL_USER: keestash
      MYSQL_PASSWORD: keestash
    ports:
      - "6033:3306"
    volumes:
      - keestash_db:/var/lib/mysql

volumes:
  keestash_db: