version: '3.3'
services:
  keestash-web:
    container_name: keestash-web
    build:
      context: ./config/docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./config/docker/web/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/docker/web/apache/keestash.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/docker/web/apache/cert.pem:/etc/apache2/ssl/cert.pem
      - ./config/docker/web/apache/cert-key.pem:/etc/apache2/ssl/cert-key.pem
    ports:
      - '8000:80'
      - '8080:443'
    networks:
      - keestash-network
  db:
    container_name: mysql8
    build:
      context: ./config/docker/db
      dockerfile: Dockerfile
    platform: linux/amd64
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keestash
      MYSQL_DATABASE: keestash
      MYSQL_USER: keestash
      MYSQL_PASSWORD: keestash
    ports:
      - "6033:3306"
    volumes:
      - keestash_db:/var/lib/mysql
      - ./:/root/
    networks:
      - keestash-network

  keestash-redis:
    image: redis:latest
    container_name: keestash-redis
    ports:
      - "6379:6379"
    networks:
      - keestash-network

  prometheus:
    container_name: prometheus
    build:
      context: ./config/docker/prometheus
      dockerfile: Dockerfile
    volumes:
      - ./config/docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # Prometheus data
    networks:
      - keestash-network
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/docker/grafana:/etc/grafana/provisioning  # Grafana provisioning files
    depends_on:
      - prometheus
    networks:
      - keestash-network
  #    restart: unless-stopped

volumes:
  keestash_db:
  grafana-data:
  prometheus-data:

networks:
  keestash-network:
    driver: bridge
