version: '3.3'
services:
  keestash-api:
    container_name: keestash-api
    build:
      context: ./config/docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./config/docker/web/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/docker/web/apache/keestash.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/docker/web/apache/cert.pem:/etc/apache2/ssl/cert.pem
      - ./config/docker/web/apache/cert-key.pem:/etc/apache2/ssl/cert-key.pem
    ports:
      - '8000:80'
      - '8080:443'
    networks:
      - keestash-network
  keestash-db:
    build:
      context: ./config/docker/db
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keestash
      MYSQL_DATABASE: keestash
      MYSQL_USER: keestash
      MYSQL_PASSWORD: keestash
    ports:
      - "6033:3306"
    volumes:
      - keestash_db:/var/lib/mysql
      - ./:/root/
    networks:
      - keestash-network

  keestash-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - keestash-network

  keestash-prometheus:
    build:
      context: ./config/docker/prometheus
      dockerfile: Dockerfile
    volumes:
      - ./config/docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # Prometheus data
    networks:
      - keestash-network
    ports:
      - '9090:9090'

  keestash-grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/docker/grafana:/etc/grafana/provisioning  # Grafana provisioning files
    depends_on:
      - keestash-prometheus
    networks:
      - keestash-network

  keestash-stripe-cli:
    build:
      context: ./config/docker/stripe
      dockerfile: Dockerfile
    environment:
      STRIPE_CLI_TELEMETRY_OPTOUT: true
    networks:
      - keestash-network
    tty: true

volumes:
  keestash_db:
  grafana-data:
  prometheus-data:

networks:
  keestash-network:
    driver: bridge
