on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Project
        run: |
          - cd apps/ && git clone https://github.com/keestash/users.git
          - cd apps/ && git clone https://github.com/keestash/password_manager.git
          - npm install
          - npm build:prod
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Nightly ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Clean Up
        run: |
          - rm -rf node_modules
          - rm -rf .github .git config/phpstan config/vagrant test/
          - rm -f .babelrc .editorconfig .eslintrc.js .gitignore Vagrantfile composer.json composer.lock package-lock.json package.json webpack.config.js