on:
  push:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Keestash Users
        uses: actions/checkout@master
        with:
          repository: keestash/users
          path: apps/
      - name: Keestash Password Manager
        uses: actions/checkout@master
        with:
          repository: keestash/password_manager
          path: apps/
      - name: Build Project
        uses: actions/setup-node@v2
        with:
          node-version: '12.18.2'
      - run: npm -v  
      - run: npm install
      - run: npm run build:prod
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Nightly ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Clean Up
        run: |
          - rm -rf node_modules
          - rm -rf .github .git config/phpstan config/vagrant test/
          - rm -f .babelrc .editorconfig .eslintrc.js .gitignore Vagrantfile composer.json composer.lock package-lock.json package.json webpack.config.js
